package installsteps

var filesToDelete = []string {
  //AerojetKerbodyne
  "/AerojetKerbodyne/Agencies",
  "/AerojetKerbodyne/Flags",
  // AIES
  "/AIES_Aerospace/Aero",
  "/AIES_Aerospace/Command/AIESorbiterpod",
  "/AIES_Aerospace/FuelTank/AIESfueltank 7k",
  "/AIES_Aerospace/FuelTank/AIESFueltank superior3",
  "/AIES_Aerospace/FuelTank/AIESFueltanksul",
  "/AIES_Aerospace/FuelTank/AIESrcs125ra",
  "/AIES_Aerospace/FuelTank/AIEStank MR1",
  "/AIES_Aerospace/FuelTank/AIEStank1300cl",
  "/AIES_Aerospace/FuelTank/AIEStankMER1",
  "/AIES_Aerospace/FuelTank/AIEStankMER6",
  "/AIES_Aerospace/FuelTank/AIEStankminsond",
  "/AIES_Aerospace/Structure/AIES *",
  "/AIES_Aerospace/Structure/AIESadapterrads",
  "/AIES_Aerospace/Structure/AIESbase*",
  "/AIES_Aerospace/Structure/AIESdec*",
  "/AIES_Aerospace/Structure/AIESdesacoplador sat1",
  // HabitatPack
  "/HabitatPack/Parts/Basemount",
  "/HabitatPack/Parts/orbitalorb",
  //DeadlyReentry
  "/DeadlyReentry/Plugins",
  "/DeadlyReentry/Sounds",
  "/DeadlyReentry/*.cfg",
  //FASA
  "/FASA/Agencies",
  "/FASA/Flags",
  "/FASA/ICBM",
  "/FASA/Mercury",
  "/FASA/Resources",
  "/FASA/Apollo/ApolloCSM",
  "/FASA/Apollo/FASA_Apollo_Fairings",
  "/FASA/Apollo/FASA_Apollo_Str",
  "/FASA/Apollo/Science",
  "/FASA/Apollo/LEM/Antennas",
  "/FASA/Apollo/LEM/AscentStage",
  "/FASA/Apollo/LEM/DescentStage",
  "/FASA/Apollo/LEM/DockingCone",
  "/FASA/Apollo/LEM/InterStage",
  "/FASA/Apollo/LEM/LandingLegs",
  "/FASA/Gemini2/FASA_Agena/*Fairing*",
  "/FASA/Gemini2/FASA_Agena/*LFT*",
  "/FASA/Gemini2/FASA_ASAS_MiniComp",
  "/FASA/Gemini2/FASA_[B-F]*",
  "/FASA/Gemini2/FASA_Gemini_[A-K]*",
  "/FASA/Gemini2/FASA_Gemini_La*",
  "/FASA/Gemini2/FASA_Gemini_LES",
  "/FASA/Gemini2/FASA_Gemini_LFT",
  "/FASA/Gemini2/FASA_Gemini_LFTLong",
  "/FASA/Gemini2/FASA_Gemini_LR91_Pack/*Fairing*",
  "/FASA/Gemini2/FASA_Gemini_LR91_Pack/*LFT*",
  "/FASA/Gemini2/FASA_Gemini_[M-R]*",
  "/FASA/Gemini2/FASA_Gemini_SAS_RCS",
  "/FASA/Gemini2/FASA_WingGemini",
  "/FASA/Gemini2/SmallGearBay",
  "/FASA/Probes/Explorer",
  "/FASA/Probes/Pioneer",
  "/FASA/Probes/Probe_Parachute_Box",
  // DMagic
  "/DMagicOrbitalScience/Flags",
  "/DMagicOrbitalScience/UniversalStorage",
  //DiminishingRTG
  "DiminishingRTG/RTGResourses.cfg",
  // KW Rocketry
  "/KWRocketry/Flags",
  "/KWRocketry/Parts/Fuel/KW_Universal_Tanks/[1|3-9]*",
  "/KWRocketry/Parts/Fuel/KW_Universal_Tanks/2[^0]*",
  "/KWRocketry/Parts/Fuel/KW_Universal_Tanks/KW_[C-R]*",
  "/KWRocketry/Parts/Fuel/KW_Universal_Tanks/[L-Z]*",
  "/KWRocketry/Parts/Fuel/KW_Universal_Tanks/KW_AdapterF*",
  "/KWRocketry/Parts/Control/KWRadialSAS",
  "/KWRocketry/Parts/Structural/KWFuelAdapter",
  // mechjeb2
  "/MechJeb2/Parts",
  // RealChute
  "/RealChute/Flags",
  // kOS
  "/kOS/Flags",
  // 000_USITools
  "/000_USITools/Flags",
  // MagicSmokeIndustries
  "/MagicSmokeIndustries/Flags",
  // Kerbaltek
  "/Kerbaltek/Flags",
  // Kanadarm
  "RKE_Kanadarm/Flags",
  "RKE_Kanadarm/Models/a*",
  "RKE_Kanadarm/Models/e*",
  "RKE_Kanadarm/Models/flag*",
  "RKE_Kanadarm/Models/m*",
  "RKE_Kanadarm/Models/r*",
  "RKE_Kanadarm/Models/s*",
  "RKE_Kanadarm/Parts/a*",
  "RKE_Kanadarm/Parts/e*",
  "RKE_Kanadarm/Parts/r*",
  "RKE_Kanadarm/Parts/s*",
  "RKE_Kanadarm/Sounds",
  // NovaPunch2
  "/NovaPunch2/Agencies",
  "/NovaPunch2/Flags",
  "/NovaPunch2/Parts/ControlPods",
  "/NovaPunch2/Parts/Fairings",
  "/NovaPunch2/Parts/FuelTanks",
  "/NovaPunch2/Parts/NoseCone",
  "/NovaPunch2/Parts/SAS",
  "/NovaPunch2/Parts/YawmasterCSM",
  "/NovaPunch2/Parts/RCS",
  "/NovaPunch2/Parts/CouplersAndAdapters/NP_interstage*",
  "/NovaPunch2/Parts/Freyja/FreyjaEng",
  "/NovaPunch2/Parts/Freyja/FreyjaRCS",
  "/NovaPunch2/Parts/Freyja/FreyjaTrunk",
  "/NovaPunch2/Parts/Odin2/OdinFairings",
  "/NovaPunch2/Parts/Odin2/OdinPod",
  "/NovaPunch2/Parts/Odin2/OdinRCS",
  "/NovaPunch2/Parts/Odin2/OdinServiceModule",
  "/NovaPunch2/Parts/Thor/NP_ThorLanderRCS",
  "/NovaPunch2/Parts/Thor/NP_ThorLanderRCSTank",
  "/NovaPunch2/Parts/Thor/NP_ThorAscentPackage",
  "/NovaPunch2/Parts/Thor/NP_ThorDescentPackage",
  "/NovaPunch2/Parts/Thor/NP_ThorLanderStrut2",
  "/NovaPunch2/Parts/Thor/NP_ThorLanderASAS",
  "/NovaPunch2/Parts/Parachutes/NP_chute_FuelTankCapParachute",
  "/NovaPunch2/Parts/Misc/NP_Leg_HeavyLeg",
  "/NovaPunch2/Parts/LaunchEscape/NP_LES_RCS_nanocone",
  "/NovaPunch2/Parts/Odin2/OdinShield",
  // SpaceY
  "/SpaceY-Lifters/Agencies",
  "/SpaceY-Lifters/Flags",
  "/SpaceY-Lifters/Sounds",
  "/SpaceY-Lifters/Parts/C*",
  "/SpaceY-Lifters/Parts/De*",
  "/SpaceY-Lifters/Parts/F*",
  "/SpaceY-Lifters/Parts/H*",
  "/SpaceY-Lifters/Parts/L*",
  "/SpaceY-Lifters/Parts/R*",
  "/SpaceY-Lifters/Parts/S*",
  "/SpaceY-Lifters/Parts/T*",
  "/SpaceY-Lifters/Parts/Docking/SYdocking3m.*",
  "/SpaceY-Lifters/0_TechTree.cfg",
  "/SpaceY-Lifters/CTTpatch.cfg",
  "/SpaceY-Lifters/SpaceY_CustomSounds.cfg",
  "/SpaceY-Lifters/SpaceY_ModularFuelTanks.cfg",
  "/SpaceY-Lifters/SpaceY-DeadlyReentry.cfg",
  // Squad
  "/Squad/Agencies",
  "/Squad/Flags",
  "/Squad/Parts/Aero/fairings",
  "/Squad/Parts/FuelTank/RCSFuel*",
  "/Squad/Parts/FuelTank/Size3*",
  "/Squad/Parts/FuelTank/adapter*",
  "/Squad/Parts/FuelTank/fuelTankJ*",
  "/Squad/Parts/FuelTank/fuelTankO*",
  "/Squad/Parts/FuelTank/fuelTankT100",
  "/Squad/Parts/FuelTank/fuelTankT200",
  "/Squad/Parts/FuelTank/fuelTankT400",
  "/Squad/Parts/FuelTank/fuelTankT800",
  "/Squad/Parts/FuelTank/fuelTankX*",
  "/Squad/Parts/FuelTank/mk3*",
  "/Squad/Parts/FuelTank/xenon*",
  //StockBugFixModules
  "/StockBugFixModules/BandwidthFix",
  "/StockBugFixModules/SymmetryActionFix",
  // UKS/MKS
  "/UmbraSpaceIndustries/Kolonization/Flags",
  "/UmbraSpaceIndustries/Kolonization/Parts/MK3*",
  "/UmbraSpaceIndustries/Kolonization/Parts/MKS_[A-Q]*",
  "/UmbraSpaceIndustries/Kolonization/Parts/MKS_[S-Z]*",
  "/UmbraSpaceIndustries/Kolonization/Parts/MKV_Ag*",
  "/UmbraSpaceIndustries/Kolonization/Parts/MKV_[B|L|W]*",
  "/UmbraSpaceIndustries/Kolonization/Parts/MKV_Pod.cfg",
  "/UmbraSpaceIndustries/Kolonization/Parts/MiniRover.cfg",
  "/UmbraSpaceIndustries/Kolonization/Parts/OKS_[A|K|P-S|W]*",
  "/UmbraSpaceIndustries/Kolonization/Parts/OKS_Col*",
  "/UmbraSpaceIndustries/Kolonization/Parts/OKS_Ha*",
  "/UmbraSpaceIndustries/Kolonization/Parts/OctoLander.cfg",
  "/UmbraSpaceIndustries/Kolonization/Parts/ScanOMatic.cfg",
  "/UmbraSpaceIndustries/Kontainers/Kontainer*",
  "/UmbraSpaceIndustries/Kontainers/Assets/Kontainer*",
  // UniversalStorage
  "/UniversalStorage/Flags",
  // TACLS
  "/ThunderAerospace/TacLifeSupport[A-Q]*",
  // Talisar Parts
  "TalisarParts/Resources",
  "TalisarParts/Parts/Command",
  "TalisarParts/Parts/FuelTank",
  "TalisarParts/Parts/Science",
  "TalisarParts/Parts/Structural",
  // Taurus HCV
  "/RSCapsuledyne/Parts/Engine",
  "/RSCapsuledyne/Parts/FuelTank",
  "/RSCapsuledyne/Parts/OreTank",
  "/RSCapsuledyne/Parts/Nuke",
  // Realism Overhaul
  "/RealismOverhaul/Parts/NoseconeCockpit",
  // Version files of all other mods
  "/[0-9A-Ja-jL-Zl-z]*/*.version",
  "/[Kk][A-Ra-rT-Zt-z]*/*.version",
  "/KSP-*/*.version",
  "/*/*/*.version",
  "/*/*/*/*.version",
  "/000_Toolbar/version.txt"
}
