package installsteps

var filesToDelete = []string {
  // AIES
  "/AIES_Aerospace/Aero",
  "/AIES_Aerospace/Command/AIESorbiterpod",
  "/AIES_Aerospace/FuelTank/AIESfueltank 7k",
  "/AIES_Aerospace/FuelTank/AIESFueltank superior3",
  "/AIES_Aerospace/FuelTank/AIESFueltanksul",
  "/AIES_Aerospace/FuelTank/AIESrcs125ra",
  "/AIES_Aerospace/FuelTank/AIEStank MR1",
  "/AIES_Aerospace/FuelTank/AIEStank1300cl",
  "/AIES_Aerospace/FuelTank/AIEStankMER1",
  "/AIES_Aerospace/FuelTank/AIEStankMER6",
  "/AIES_Aerospace/FuelTank/AIEStankminsond",
  "/AIES_Aerospace/Structure/AIES *",
  "/AIES_Aerospace/Structure/AIESadapterrads",
  "/AIES_Aerospace/Structure/AIESbase*",
  "/AIES_Aerospace/Structure/AIESdec*",
  "/AIES_Aerospace/Structure/AIESdesacoplador sat1",
  // HabitatPack
  "/HabitatPack/Parts/Basemount",
  "/HabitatPack/Parts/orbitalorb",
  //DeadlyReentry
  "/DeadlyReentry/Plugins",
  "/DeadlyReentry/Sounds",
  "/DeadlyReentry/*.cfg",
  //FASA
  "/FASA/Agencies",
  "/FASA/Flags",
  "/FASA/ICBM",
  "/FASA/Mercury",
  "/FASA/Resources",
  "/FASA/Apollo/ApolloCSM",
  "/FASA/Apollo/FASA_Apollo_Fairings",
  "/FASA/Apollo/FASA_Apollo_Str",
  "/FASA/Apollo/Science",
  "/FASA/Apollo/LEM/Antennas",
  "/FASA/Apollo/LEM/AscentStage",
  "/FASA/Apollo/LEM/DescentStage",
  "/FASA/Apollo/LEM/DockingCone",
  "/FASA/Apollo/LEM/InterStage",
  "/FASA/Apollo/LEM/LandingLegs",
  "/FASA/Gemini2/FASA_ASAS_MiniComp",
  "/FASA/Gemini2/FASA_Fairings_Plate_2m",
  "/FASA/Gemini2/FASA_Gemini_BigG",
  "/FASA/Gemini2/FASA_Gemini_Dec_Dark",
  "/FASA/Gemini2/FASA_Gemini_Engine_Fuel2",
  "/FASA/Gemini2/FASA_Gemini_LES",
  "/FASA/Gemini2/FASA_Gemini_LFT",
  "/FASA/Gemini2/FASA_Gemini_LFTLong",
  "/FASA/Gemini2/FASA_Gemini_Lander_Eng",
  "/FASA/Gemini2/FASA_Gemini_Lander_Legs",
  "/FASA/Gemini2/FASA_Gemini_Lander_Pod",
  "/FASA/Gemini2/FASA_Gemini_MOL",
  "/FASA/Gemini2/FASA_Gemini_NoseCone2",
  "/FASA/Gemini2/FASA_Gemini_Parachute2",
  "/FASA/Gemini2/FASA_Gemini_Pod2",
  "/FASA/Gemini2/FASA_Gemini_RCS_Thruster",
  "/FASA/Gemini2/FASA_Gemini_SAS_RCS",
  "/FASA/Gemini2/FASA_WingGemini",
  "/FASA/Gemini2/SmallGearBay",
  "/FASA/Gemini2/FASA_Gemini_Centaur",
  "/FASA/Gemini2/FASA_Gemini_LR91_Pack/*Fairing*",
  "/FASA/Gemini2/FASA_Gemini_LR91_Pack/*LFT*",
  "/FASA/Gemini2/FASA_Agena/*Fairing*",
  "/FASA/Gemini2/FASA_Agena/*LFT*",
  "/FASA/Probes/Explorer",
  "/FASA/Probes/Pioneer",
  "/FASA/Probes/Probe_Parachute_Box",
  // DMagic
  "/DMagicOrbitalScience/UniversalStorage",
  // KW Rocketry
  "/KWRocketry/Parts/Fuel/KW_Universal_Tanks/1*",
  "/KWRocketry/Parts/Fuel/KW_Universal_Tanks/2_*",
  "/KWRocketry/Parts/Fuel/KW_Universal_Tanks/2m*",
  "/KWRocketry/Parts/Fuel/KW_Universal_Tanks/3*",
  "/KWRocketry/Parts/Fuel/KW_Universal_Tanks/5*",
  "/KWRocketry/Parts/Fuel/KW_Universal_Tanks/KW_C*",
  "/KWRocketry/Parts/Fuel/KW_Universal_Tanks/KW_F*",
  "/KWRocketry/Parts/Fuel/KW_Universal_Tanks/P*",
  "/KWRocketry/Parts/Fuel/KW_Universal_Tanks/R*",
  "/KWRocketry/Parts/Fuel/KW_Universal_Tanks/KW_AdapterF*",
  "/KWRocketry/Parts/Control/KWRadialSAS",
  "/KWRocketry/Parts/Structural/KWFuelAdapter",
  // mechjeb2
  "/MechJeb2/Parts",
  // NovaPunch2
  "/NovaPunch2/Agencies",
  "/NovaPunch2/Flags",
  "/NovaPunch2/Parts/ControlPods",
  "/NovaPunch2/Parts/Fairings",
  "/NovaPunch2/Parts/FuelTanks",
  "/NovaPunch2/Parts/NoseCone",
  "/NovaPunch2/Parts/SAS",
  "/NovaPunch2/Parts/YawmasterCSM",
  "/NovaPunch2/Parts/RCS",
  "/NovaPunch2/Parts/CouplersAndAdapters/NP_interstage*",
  "/NovaPunch2/Parts/Freyja/FreyjaEng",
  "/NovaPunch2/Parts/Freyja/FreyjaRCS",
  "/NovaPunch2/Parts/Freyja/FreyjaTrunk",
  "/NovaPunch2/Parts/Odin2/OdinFairings",
  "/NovaPunch2/Parts/Odin2/OdinPod",
  "/NovaPunch2/Parts/Odin2/OdinRCS",
  "/NovaPunch2/Parts/Odin2/OdinServiceModule",
  "/NovaPunch2/Parts/Thor/NP_ThorLanderRCS",
  "/NovaPunch2/Parts/Thor/NP_ThorLanderRCSTank",
  "/NovaPunch2/Parts/Thor/NP_ThorAscentPackage",
  "/NovaPunch2/Parts/Thor/NP_ThorDescentPackage",
  "/NovaPunch2/Parts/Thor/NP_ThorLanderStrut2",
  "/NovaPunch2/Parts/Thor/NP_ThorLanderASAS",
  "/NovaPunch2/Parts/Parachutes/NP_chute_FuelTankCapParachute",
  "/NovaPunch2/Parts/Misc/NP_Leg_HeavyLeg",
  "/NovaPunch2/Parts/LaunchEscape/NP_LES_RCS_nanocone",
  "/NovaPunch2/Parts/Odin2/OdinShield",
  // Squad
  "/Squad/Agencies",
  "/Squad/Flags",
  "/Squad/Parts/Aero/fairings",
  "/Squad/Parts/FuelTank/RCSFuel*",
  "/Squad/Parts/FuelTank/Size3*",
  "/Squad/Parts/FuelTank/adapter*",
  "/Squad/Parts/FuelTank/fuelTankJ*",
  "/Squad/Parts/FuelTank/fuelTankO*",
  "/Squad/Parts/FuelTank/fuelTankT100",
  "/Squad/Parts/FuelTank/fuelTankT200",
  "/Squad/Parts/FuelTank/fuelTankT400",
  "/Squad/Parts/FuelTank/fuelTankT800",
  "/Squad/Parts/FuelTank/fuelTankX*",
  "/Squad/Parts/FuelTank/mk2*",
  "/Squad/Parts/FuelTank/mk3*",
  "/Squad/Parts/FuelTank/xenon*",
  // UKS/MKS
  "/UmbraSpaceIndustries/Kolonization/Flags",
  "/UmbraSpaceIndustries/Kolonization/Parts/MK3*",
  "/UmbraSpaceIndustries/Kolonization/Parts/MKS_A*",
  "/UmbraSpaceIndustries/Kolonization/Parts/MKS_C*",
  "/UmbraSpaceIndustries/Kolonization/Parts/MKS_D*",
  "/UmbraSpaceIndustries/Kolonization/Parts/MKS_E*",
  "/UmbraSpaceIndustries/Kolonization/Parts/MKS_F*",
  "/UmbraSpaceIndustries/Kolonization/Parts/MKS_K*",
  "/UmbraSpaceIndustries/Kolonization/Parts/MKS_L*",
  "/UmbraSpaceIndustries/Kolonization/Parts/MKS_M*",
  "/UmbraSpaceIndustries/Kolonization/Parts/MKS_P*",
  "/UmbraSpaceIndustries/Kolonization/Parts/MKS_S*",
  "/UmbraSpaceIndustries/Kolonization/Parts/MKS_W*",
  "/UmbraSpaceIndustries/Kolonization/Parts/MKV_Ag*",
  "/UmbraSpaceIndustries/Kolonization/Parts/MKV_B*",
  "/UmbraSpaceIndustries/Kolonization/Parts/MKV_L*",
  "/UmbraSpaceIndustries/Kolonization/Parts/MKV_Pod.cfg",
  "/UmbraSpaceIndustries/Kolonization/Parts/MKV_W*",
  "/UmbraSpaceIndustries/Kolonization/Parts/MiniRover.cfg",
  "/UmbraSpaceIndustries/Kolonization/Parts/OKS_A*",
  "/UmbraSpaceIndustries/Kolonization/Parts/OKS_Col*",
  "/UmbraSpaceIndustries/Kolonization/Parts/OKS_Ha*",
  "/UmbraSpaceIndustries/Kolonization/Parts/OKS_K*",
  "/UmbraSpaceIndustries/Kolonization/Parts/OKS_P*",
  "/UmbraSpaceIndustries/Kolonization/Parts/OKS_S*",
  "/UmbraSpaceIndustries/Kolonization/Parts/OKS_W*",
  "/UmbraSpaceIndustries/Kolonization/Parts/OctoLander.cfg",
  "/UmbraSpaceIndustries/Kolonization/Parts/ScanOMatic.cfg",
  "/UmbraSpaceIndustries/Kontainers/Kontainer*",
  "/UmbraSpaceIndustries/Kontainers/Assets/Kontainer*",
  // UniversalStorage
  "/UniversalStorage/Flags",
  // TACLS
  "/ThunderAerospace/TacLifeSupportContainers",
  "/ThunderAerospace/TacLifeSupportHexCans",
  "/ThunderAerospace/TacLifeSupportMFT",
  // Taurus HCV
  "/RSCapsuledyne/Parts/Engine",
  "/RSCapsuledyne/Parts/FuelTank",
  "/RSCapsuledyne/Parts/OreTank",
  "/RSCapsuledyne/Parts/Nuke",
  // Realism Overhaul
  "/RealismOverhaul/Parts/NoseconeCockpit",
}
